### ISSUE TITLE
IR lib for esp8266_rtos_sdk

### ISSUE THREAD

**Issue by lhdxb69** [valkuc/esp8266-ir-remote#1]
Hi, thank you for your esp8266 ir library.
I tested this successfully with esp8266_nonos_sdk, but can not on esp8266_rtos_sdk.
Look forward to your help.

**Comment by valkuc** [comment]
Hello, there are two branches: sdk and rtos_sdk, so you need to switch to rtos_sdk branch. But there can be another problem. The code last tested on SDK v1.5.2 few years ago and I don't know if it will work without changes on newer version and currently I don't have time to investigate that.

**Comment by lhdxb69** [comment]
Very thank you :)
